apiVersion: v1
kind: Service
metadata:
   name: timeoffapp
   labels:
    run: timeoff
spec:
   ports:
   - port: 80
     targetPort: 3000
     protocol: TCP
   type: NodePort
   selector:
     app: timeoff
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
   name: timeoffapp
spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: timeoff
     spec:
       containers:
       - name: timeoffapp
         image: timeoffapp:v1
         command: ["npm"]
         args: ["start"]         
         ports:
         - containerPort: 3000
         env:
         - name: NODE_ENV
           value: production
         - name: BLUEFYRE_AGENT_ID
           valueFrom:
             secretKeyRef:
               name: bluefyre-agent-id
               key: agentid         
         - name: MYSQL_HOST
           value: timeoffapp-mysql
         - name: MYSQL_DATABASE
           value: timeoffappnoagent
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-pass
               key: password
